version: "3.9"

services:
  postgres:
    image: 'postgres:15'
    container_name: postgres_local
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    labels:
      org.springframework.boot.jdbc.parameters: currentSchema=transformer
      org.springframework.boot.service-connection: postgres

volumes:
  postgres_data:
